name: CI
on: [push, pull_request]
jobs:
  test-and-coverage:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python requirements
      run: pip install -r requirements.txt
    - name: Test
      run: pytest --cov
    - name: Upload coverage to Codecov (ubuntu-latest only)
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == "3.11"
      uses: codecov/codecov-action@v3
