name: CI
on: [push, pull_request]
jobs:
  test-and-coverage:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install Python requirements
      run: pip install -r requirements.txt
    - name: Test
      run: pytest --cov --cov-report html
    - name: Upload coverage to Codecov (ubuntu-latest only)
      if: matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v3
